---
- name: configure ldap authentication
  lineinfile:
    path: /etc/pam.d/common-auth
    line: 'account required    pam_access.so'

- name: configure passwd authentication
  template:
    src: command-password
    dest: /etc/pam.d/common-password

- name: Auto-create home directories
  lineinfile:
    path: /etc/pam.d/common-session
    line: 'session required pam_mkhomedir.so skel=/etc/skel umask=0022'
