---
# This playbook deploys a multi-master LDAP cluster and a Linux client

- name: Setup LDAP servers
  hosts: server
  become: "yes"
  roles:
    - ldap-server

- name: Generate CA Certificate
  hosts: initial
  become: "yes"
  roles:
    - ldap-cacert

- name: Setup LDAP Replication
  hosts: server
  become: "yes"
  roles:
    - ldap-replicate

- name: Configure LDAP Servers
  hosts: server
  become: "yes"
  roles:
    - ldap-config

- name: Install OpenLDAP client
  hosts: client
  become: "yes"
  roles:
    - ldap-client
