---
- name: Generate the root password for ldap
  shell: slappasswd -h {ssha} -s {{ openldap_rootpw }}
  register: root_password
  changed_when: "False"

- name: Fix the Password
  set_fact:
    rootPW: '{{ root_password.stdout | trim }}'

- name: Set the DN
  ldap_attr:
    dn: olcDatabase={0}config,cn=config
    name: olcRootDN
    values: cn=admin,cn=config
    state: exact

- name: Set the root password
  ldap_attr:
    dn: olcDatabase={0}config,cn=config
    name: olcRootPW
    values: "{{ rootPW }}"
    state: exact
