---
- name: enable logging
  ldap_attr:
    dn: cn=config
    name: olcLogLevel
    values: stats
    state: exact

- name: pipe ldap logs to logfile
  template:
    src: slapd.conf.j2
    dest: /etc/rsyslog.d/10-slapd.conf
    owner: root
    mode: 0755

- name: restart slapd
  service:
    name: slapd
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
