---
- name: Create MD5 Hash
  command: "slappasswd -v -h {md5} -s {{ openldap_userpw }}"
  register: md5_user
  changed_when: "False"

- name: Store MD5 Hash
  set_fact:
    md5user: '{{ md5_user.stdout | trim }}'

- name: Create User Account
  ldap_entry:
    dn: "uid=jdoe,ou=users,dc={{ openldap_domain_middle }},dc={{ openldap_domain_top }}"
    bind_dn: "cn=admin,dc={{ openldap_domain_middle }},dc={{ openldap_domain_top }}"
    bind_pw: "{{ openldap_adminpw }}"
    start_tls: "{{ tls }}"
    validate_certs: "no"
    objectClass:
      - posixAccount
      - person
    attributes:
      cn: John
      sn: Doe
      userPassword: "{{ md5user }}"
      loginShell: /bin/bash
      uidNumber: 5000
      gidNumber: 4000
      homeDirectory: /home/jdoe
      uid: jdoe

- name: Create User Group
  ldap_entry:
    dn: "cn=sysadmins,ou=groups,dc={{ openldap_domain_middle }},dc={{ openldap_domain_top }}"
    bind_dn: "cn=admin,dc={{ openldap_domain_middle }},dc={{ openldap_domain_top }}"
    bind_pw: "{{ openldap_adminpw }}"
    start_tls: "{{ tls }}"
    validate_certs: "no"
    objectClass:
      - posixGroup
    attributes:
      gidNumber: 4000
      memberUid: jdoe
