---
- name: Copy CACert to server
  copy:
    src: "{{ local_certs_path }}{{ item }}"
    dest: "{{ item }}"
  with_items:
    - /etc/ssl/certs/cacert.pem
    - /etc/ssl/private/cakey.pem
  when: tls == "yes"

- name: Setup server certs
  import_tasks: setup_server_certs.yml
  when: tls == "yes"

- name: Setup tls
  import_tasks: setup_tls.yml
  when: tls == "yes"

- name: Create Groups
  import_tasks: create_groups.yml

- name: Create Proxy User
  import_tasks: create_proxy_user.yml

- name: Create User
  import_tasks: create_user.yml
