---
- name: generate slapd key
  command: certtool --generate-privkey \
    --bits 2048 \
    --outfile /etc/ssl/private/ldap_slapd_key.pem
  changed_when: "False"

# - debug:
#     msg: "{{ cacert }}"

- name: ldap.info template
  template:
    src: ldap.info.j2
    dest: /etc/ssl/ldap.info
    owner: root
    mode: 0755

- name: Create the server's certificate
  command: certtool --generate-certificate \
    --load-privkey /etc/ssl/private/ldap_slapd_key.pem \
    --load-ca-certificate /etc/ssl/certs/cacert.pem \
    --load-ca-privkey /etc/ssl/private/cakey.pem \
    --template /etc/ssl/ldap.info \
    --outfile /etc/ssl/certs/ldap_slapd_cert.pem
  changed_when: "False"

- name: Set perms on key
  file:
    path: /etc/ssl/private/ldap_slapd_key.pem
    group: openldap
    mode: 0640

- name: Add Openldap user to ssl-cert group
  user:
    name: openldap
    groups: ssl-cert
    append: "yes"

- name: Restart slapd
  service:
    name: slapd
    state: restarted
