---
- name: Create certinfo.ldif for setting certificate paths
  template:
    src: certinfo.j2
    dest: /root/certinfo.ldif
    owner: root
    mode: 0755

- name: Set certificate paths in LDAP config
  command: "ldapmodify -D cn=admin,cn=config -f \
           /root/certinfo.ldif -w{{ openldap_rootpw }}"
  changed_when: "false"

- name: enable TLS
  ldap_attr:
    dn: olcDatabase={1}mdb,cn=config
    bind_dn: cn=admin,cn=config
    bind_pw: "{{ openldap_rootpw }}"
    name: olcSecurity
    values: tls=1
    state: exact

- name: add TLS cert to local LDAP
  lineinfile:
    path: /etc/ldap/ldap.conf
    regexp: '^TLS_CACERT'
    line: 'TLS_CACERT /etc/ssl/certs/cacert.pem'

- name: restart slapd
  service:
    name: slapd
    state: restarted
