---
- name: Generate Private Key
  shell: certtool --generate-privkey > /etc/ssl/private/cakey.pem
  changed_when: "False"

- name: ca info
  template:
    src: ca.info.j2
    dest: /etc/ssl/ca.info
    owner: root
    mode: 0755

- name: create cacert
  command: certtool --generate-self-signed \
    --load-privkey /etc/ssl/private/cakey.pem \
    --template /etc/ssl/ca.info \
    --outfile /etc/ssl/certs/cacert.pem
  changed_when: "False"

## Eventually pick up the cert from here via fact
- name: store cacert
  command: cat /etc/ssl/certs/cacert.pem
  register: cacertdirty
  changed_when: "False"

- name: Store cacert
  set_fact:
    cacert: '{{ cacertdirty.stdout | trim }}'

- name: fetch cacert
  fetch:
    src: "{{ item }}"
    dest: "{{ local_certs_path }}{{ item }}"
    flat: "yes"
  with_items:
    - /etc/ssl/private/cakey.pem
    - /etc/ssl/certs/cacert.pem
